%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%   BOS RANDOM DOT BACKGROUND GENERATOR
%
%   Saves the SAME random BOS pattern as:
%       1. SVG
%       2. PNG
%
%   Output folder:
%       BOS Backgrounds
%
%   Camera frame:
%       256 x 256 pixels
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clc;
clear;
close all;

%% =====================================================
%  USER INPUTS
% ======================================================

% ------------------------------------------------------
% Camera frame used during BOS testing
% ------------------------------------------------------

camera_width_px  = 256;
camera_height_px = 256;

% ------------------------------------------------------
% Physical field of view at BACKGROUND plane
% ------------------------------------------------------

% Measure the physical width and height of the background
% visible in the 256 x 256 camera frame.
%
% Example:
%
% 300 mm x 300 mm of background is visible.

FOV_width_mm  = 300;
FOV_height_mm = 300;

% ------------------------------------------------------
% Desired apparent dot diameter on camera
% ------------------------------------------------------

% Typical BOS target:
%
% approximately 2 - 3 pixels

target_dot_pixels = 2.5;

% ------------------------------------------------------
% Physical printed background size
% ------------------------------------------------------

% The poster only needs to be larger than the camera FOV.

poster_width_mm  = 500;
poster_height_mm = 350;

% ------------------------------------------------------
% Pattern density
% ------------------------------------------------------

% Approximate fraction of the background covered
% by black dots.
%
% 0.30 = approximately 30%

target_black_fraction = 0.30;

% ------------------------------------------------------
% Random dot size variation
% ------------------------------------------------------

% 0.20 = +/- 20% variation in dot diameter

diameter_jitter = 0.20;

% ------------------------------------------------------
% PNG print resolution
% ------------------------------------------------------

% 300 dpi = good
% 600 dpi = very good

print_resolution_dpi = 600;

% ------------------------------------------------------
% Random seed
% ------------------------------------------------------

% Same seed = same pattern every time.

random_seed = 1;

rng(random_seed);

% ------------------------------------------------------
% Output filename
% ------------------------------------------------------

base_filename = ...
    'BOS_random_dot_background';

%% =====================================================
%  CREATE OUTPUT FOLDER
% ======================================================

output_folder = ...
    fullfile( ...
    pwd, ...
    'BOS Backgrounds');

if ~exist(output_folder, 'dir')

    mkdir(output_folder);

end

svg_file = ...
    fullfile( ...
    output_folder, ...
    [base_filename '.svg']);

png_file = ...
    fullfile( ...
    output_folder, ...
    [base_filename '.png']);

%% =====================================================
%  CHECK CAMERA / FOV SCALE
% ======================================================

mm_per_camera_pixel_x = ...
    FOV_width_mm / ...
    camera_width_px;

mm_per_camera_pixel_y = ...
    FOV_height_mm / ...
    camera_height_px;

% For square camera pixels and no geometric distortion,
% these should be approximately equal.

scale_difference_percent = ...
    100 * ...
    abs( ...
    mm_per_camera_pixel_x - ...
    mm_per_camera_pixel_y) / ...
    mean([ ...
    mm_per_camera_pixel_x, ...
    mm_per_camera_pixel_y]);

if scale_difference_percent > 1

    warning( ...
        ['Horizontal and vertical physical scales differ ' ...
        'by %.2f%%. Check FOV dimensions.'], ...
        scale_difference_percent);

end

% Use average physical scale to define dot diameter.

mm_per_camera_pixel = ...
    mean([ ...
    mm_per_camera_pixel_x, ...
    mm_per_camera_pixel_y]);

%% =====================================================
%  CALCULATE PHYSICAL DOT SIZE
% ======================================================

nominal_dot_diameter_mm = ...
    target_dot_pixels * ...
    mm_per_camera_pixel;

nominal_dot_area_mm2 = ...
    pi * ...
    (nominal_dot_diameter_mm / 2)^2;

poster_area_mm2 = ...
    poster_width_mm * ...
    poster_height_mm;

%% =====================================================
%  CHECK POSTER SIZE
% ======================================================

if poster_width_mm < FOV_width_mm

    warning( ...
        'Poster width is smaller than camera FOV width.');

end

if poster_height_mm < FOV_height_mm

    warning( ...
        'Poster height is smaller than camera FOV height.');

end

%% =====================================================
%  CALCULATE NUMBER OF RANDOM DOTS
% ======================================================

% Randomly placed dots are allowed to overlap.
%
% Expected covered fraction:
%
% f = 1 - exp(-N*A_dot/A_total)
%
% Therefore:
%
% N = -ln(1-f)*A_total/A_dot

number_of_dots = ...
    round( ...
    -log(1 - target_black_fraction) * ...
    poster_area_mm2 / ...
    nominal_dot_area_mm2);

%% =====================================================
%  GENERATE RANDOM DOT LOCATIONS
% ======================================================

x_mm = ...
    poster_width_mm * ...
    rand(number_of_dots, 1);

y_mm = ...
    poster_height_mm * ...
    rand(number_of_dots, 1);

%% =====================================================
%  GENERATE RANDOM DOT DIAMETERS
% ======================================================

diameter_factor = ...
    1 + ...
    diameter_jitter * ...
    (2 * rand(number_of_dots,1) - 1);

dot_diameter_mm = ...
    nominal_dot_diameter_mm .* ...
    diameter_factor;

dot_radius_mm = ...
    dot_diameter_mm / 2;

%% =====================================================
%  DISPLAY PARAMETERS
% ======================================================

fprintf('\n');

fprintf( ...
    '============================================================\n');

fprintf( ...
    '                 BOS BACKGROUND PARAMETERS\n');

fprintf( ...
    '============================================================\n');

fprintf( ...
    'Camera frame                  : %d x %d pixels\n', ...
    camera_width_px, ...
    camera_height_px);

fprintf( ...
    'Background FOV                : %.3f x %.3f mm\n', ...
    FOV_width_mm, ...
    FOV_height_mm);

fprintf( ...
    'Horizontal physical scale     : %.5f mm/pixel\n', ...
    mm_per_camera_pixel_x);

fprintf( ...
    'Vertical physical scale       : %.5f mm/pixel\n', ...
    mm_per_camera_pixel_y);

fprintf( ...
    'Target dot diameter           : %.2f camera pixels\n', ...
    target_dot_pixels);

fprintf( ...
    'Nominal physical dot diameter : %.4f mm\n', ...
    nominal_dot_diameter_mm);

fprintf( ...
    'Target black coverage         : %.1f %%\n', ...
    target_black_fraction * 100);

fprintf( ...
    'Number of dots                : %d\n', ...
    number_of_dots);

fprintf( ...
    'Poster size                   : %.1f x %.1f mm\n', ...
    poster_width_mm, ...
    poster_height_mm);

fprintf( ...
    'PNG resolution                : %d dpi\n', ...
    print_resolution_dpi);

fprintf( ...
    '============================================================\n');

%% =====================================================
%  SAVE SVG
% ======================================================

fid = ...
    fopen( ...
    svg_file, ...
    'w');

if fid == -1

    error( ...
        'Could not open SVG output file.');

end

%% SVG HEADER

fprintf( ...
    fid, ...
    ['<svg xmlns="http://www.w3.org/2000/svg" ' ...
    'width="%.4fmm" height="%.4fmm" ' ...
    'viewBox="0 0 %.4f %.4f">\n'], ...
    poster_width_mm, ...
    poster_height_mm, ...
    poster_width_mm, ...
    poster_height_mm);

%% WHITE BACKGROUND

fprintf( ...
    fid, ...
    ['<rect x="0" y="0" ' ...
    'width="%.4f" height="%.4f" ' ...
    'fill="white"/>\n'], ...
    poster_width_mm, ...
    poster_height_mm);

%% RANDOM BLACK DOTS

for i = 1:number_of_dots

    fprintf( ...
        fid, ...
        ['<circle cx="%.5f" cy="%.5f" ' ...
        'r="%.5f" fill="black"/>\n'], ...
        x_mm(i), ...
        y_mm(i), ...
        dot_radius_mm(i));

end

%% SVG END

fprintf( ...
    fid, ...
    '</svg>\n');

fclose(fid);

%% =====================================================
%  CREATE PNG
% ======================================================

poster_width_px = ...
    round( ...
    (poster_width_mm / 25.4) * ...
    print_resolution_dpi);

poster_height_px = ...
    round( ...
    (poster_height_mm / 25.4) * ...
    print_resolution_dpi);

px_per_mm = ...
    print_resolution_dpi / 25.4;

% 255 = white
% 0   = black

img = ...
    255 * ones( ...
    poster_height_px, ...
    poster_width_px, ...
    'uint8');

%% =====================================================
%  DRAW SAME RANDOM DOTS INTO PNG
% ======================================================

for i = 1:number_of_dots

    x_center_px = ...
        x_mm(i) * ...
        px_per_mm;

    y_center_px = ...
        y_mm(i) * ...
        px_per_mm;

    radius_px = ...
        dot_radius_mm(i) * ...
        px_per_mm;

    %% Bounding box

    x_min = ...
        max( ...
        1, ...
        floor(x_center_px - radius_px));

    x_max = ...
        min( ...
        poster_width_px, ...
        ceil(x_center_px + radius_px));

    y_min = ...
        max( ...
        1, ...
        floor(y_center_px - radius_px));

    y_max = ...
        min( ...
        poster_height_px, ...
        ceil(y_center_px + radius_px));

    %% Local coordinate grid

    [X, Y] = ...
        meshgrid( ...
        x_min:x_max, ...
        y_min:y_max);

    %% Circular mask

    mask = ...
        (X - x_center_px).^2 + ...
        (Y - y_center_px).^2 <= ...
        radius_px^2;

    %% Paint black

    local_patch = ...
        img( ...
        y_min:y_max, ...
        x_min:x_max);

    local_patch(mask) = ...
        0;

    img( ...
        y_min:y_max, ...
        x_min:x_max) = ...
        local_patch;

end

%% =====================================================
%  WRITE PNG
% ======================================================

imwrite( ...
    img, ...
    png_file, ...
    'png');

%% =====================================================
%  PREVIEW
% ======================================================

figure( ...
    'Color', ...
    'w');

imshow(img);

title( ...
    sprintf( ...
    ['BOS Random Dot Background | ' ...
    '%.2f Camera Pixels per Dot'], ...
    target_dot_pixels));

%% =====================================================
%  FINISHED
% ======================================================

fprintf('\n');

fprintf( ...
    'Files successfully created:\n\n');

fprintf( ...
    'SVG:\n%s\n\n', ...
    svg_file);

fprintf( ...
    'PNG:\n%s\n\n', ...
    png_file);

fprintf( ...
    'PNG raster dimensions:\n');

fprintf( ...
    '%d x %d pixels\n\n', ...
    poster_width_px, ...
    poster_height_px);

fprintf( ...
    'IMPORTANT FOR PRINTING:\n');

fprintf( ...
    '1. Print at 100%% / ACTUAL SIZE.\n');

fprintf( ...
    '2. Do NOT use "Fit to Page".\n');

fprintf( ...
    '3. SVG is preferred for professional printing.\n');

fprintf( ...
    '4. PNG should be interpreted at %d dpi.\n', ...
    print_resolution_dpi);

fprintf('\n');